default:
  image: node:18

variables:
  # GIT_DEPTH: 0
  KUBE_CONTEXT: shifter-shop/shifter-shop:primary-agent

stages:
  - build
  - test
  - pre-deploy
  # - deploy

.distributed:
  interruptible: true
  only:
    - main
    - dev
    - merge_requests
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}

build:
  stage: build
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=build

test:
  stage: test
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=test

pre-deploy-job:
  stage: pre-deploy
  extends: .distributed
  script:
    - npx nx print-affected --base=$NX_BASE --head=$NX_HEAD --type=app --select=projects
  only:
    - chore/ci

pre-deploy-k8s:
  stage: pre-deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl config get-contexts
    - kubectl config use-context "$KUBE_CONTEXT"
    - kubectl get pods
    - kubectl get pods -n default
  only:
    - chore/ci
  needs: 
    - pre-deploy-job
