workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - build
  - test
  - deploy

test:
  stage: test
  script:
    - echo "This is an empty job"

# include:
  # - local: .gitlab/client.gitlab-ci.yml
  # - local: .gitlab/admin.gitlab-ci.yml
