default:
  image: node:18

variables:
  # GIT_DEPTH: 0
  KUBE_CONTEXT: shifter-shop/shifter-shop:primary-agent

stages:
  - build
  - test
  - build-trigger
  - trigger

.distributed:
  interruptible: true
  only:
    - main
    - dev
    - merge_requests
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}

build:
  stage: build
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=build

test:
  stage: test
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=test

generate-deploy-config:
  stage: build-trigger
  extends: .distributed
  artifacts:
    expire_in: 1 week
    paths:
      - deploy-affected-config.yml
  script:
    - node ./scripts/gitlab/generate-deploy.js "$(npx nx print-affected --base=$NX_BASE --head=$NX_HEAD --type=app --select=projects)"
  only:
    - chore/ci
    - main
    - dev

deploy-affected:
  stage: trigger
  trigger:
    include:
      - artifact: deploy-affected-config.yml
        job: generate-deploy-config
    strategy: depend
  only:
    - chore/ci
    - main
    - dev