version: "3.8"
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    ports:
      - 3000:3000
    networks:
      - ss_microservices

  files-svc:
    container_name: files-svc
    build:
      context: .
      dockerfile: ./apps/files/Dockerfile
    ports:
      - 3001:3000
    networks:
      - ss_microservices

  mailer-svc:
    container_name: mailer-svc
    build:
      context: .
      dockerfile: ./apps/mailer/Dockerfile
    ports:
      - 3002:3000
    environment:
      - MAILER_DSN=${MAILER_DSN}
      - AMQP_URL=amqp://rabbitmq:5672
    networks:
      - ss_microservices
    depends_on:
      - rabbitmq
      - mailhog

  payment-svc:
    container_name: payment-svc
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
    ports:
      - 3003:3000
    environment:
      - CLIENT_URL=http://localhost:8080
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_WEBHOOK_SIGNING_SECRET=${STRIPE_WEBHOOK_SIGNING_SECRET}
      - AMQP_URL=amqp://rabbitmq:5672
    networks:
      - ss_microservices
    depends_on:
      - stripe
      - rabbitmq

  invoice-svc:
    container_name: invoice-svc
    build:
      context: .
      dockerfile: ./apps/invoice/Dockerfile
    ports:
      - 3004:3000
    networks:
      - ss_microservices

  order-svc:
    container_name: order-svc
    build:
      context: .
      dockerfile: ./apps/order/Dockerfile
    ports:
      - 3005:3000
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/orders
      - AMQP_URL=amqp://rabbitmq:5672
    networks:
      - ss_microservices
      - ss_database
    depends_on:
      - postgres
      - rabbitmq

  cart-svc:
    container_name: cart-svc
    build:
      context: .
      dockerfile: ./apps/cart/Dockerfile
    ports:
      - 3006:3000
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/cart
      - AMQP_URL=amqp://rabbitmq:5672
    networks:
      - ss_microservices
      - ss_database
    depends_on:
      - postgres
      - rabbitmq

  client:
    container_name: client
    build:
      context: ./client
      args:
        - VITE_API_URL=http://localhost:3000
    ports:
      - 8080:80
    networks:
      - ss_app

  admin:
    container_name: admin
    build:
      context: ./admin
    ports:
      - 8081:80
    networks:
      - ss_app

  postgres:
    container_name: postgres
    image: postgres:15
    volumes:
      - ss_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    networks:
      - ss_database

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - ss_microservices

  stripe:
    container_name: stripe
    image: stripe/stripe-cli:v1.14.6
    command: listen --forward-to http://payment-svc:3000/webhook
    environment:
      - STRIPE_DEVICE_NAME=shifter_shop_docker
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    networks:
      - ss_microservices

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - ss_microservices

networks:
  ss_app:
  ss_microservices:
  ss_database:

volumes:
  ss_data:
