version: "3.8"
services:
  server:
    container_name: server
    build:
      context: ./api
    ports:
      - 3000:3000
    networks:
      - ss_app
      - ss_database
    depends_on:
      - database

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 8080:80
    networks:
      - ss_app

  admin:
    container_name: admin
    build:
      context: ./admin
    ports:
      - 8081:80
    networks:
      - ss_app

  database:
    container_name: database
    image: postgres:15
    volumes:
      - ss_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    networks:
      - ss_database

networks:
  ss_app:
  ss_database:

volumes:
  ss_data:
