version: "3.8"
services:
  database:
    container_name: database
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - .db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app

  mongo:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - .mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mailer:
    container_name: mailer
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
