version: "3.8"
services:
  server:
    container_name: server
    image: node:19-alpine
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./api:/app
    ports:
      - 3000:3000
    networks:
      - nwa_app
      - nwa_database
    depends_on:
      - database

  client:
    container_name: client
    image: node:19-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --port 8000 --host"
    volumes:
      - ./client:/app
    ports:
      - 8000:8000
    networks:
      - nwa_app

  database:
    container_name: database
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - nwa_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    networks:
      - nwa_database

networks:
  nwa_app:
  nwa_database:

volumes:
  nwa_data:
