version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - .db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app

  mongo:
    container_name: mongo
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - .mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=dracula
