apiVersion: batch/v1
kind: Job
metadata:
  name: secret-storage
spec:
  template:
    metadata:
      name: secret-storage
    spec:
      restartPolicy: Never
      serviceAccount: shifter-shop-api
      volumes:
        - name: secret-storage
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "secret-manager"
      containers:
        - name: busybox
          image: busybox:1.28
          command: ["sh", "-c", "echo 'Loaded secrets...'"]
          volumeMounts:
            - name: secret-storage
              mountPath: "/mnt/secrets"
              readOnly: true