apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-manager
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/shifter-shop/secrets/jwt-secret/versions/latest"
        fileName: jwt-secret.txt
      - resourceName: "projects/shifter-shop/secrets/mailer-dsn/versions/latest"
        fileName: mailer-dsn.txt
      - resourceName: "projects/shifter-shop/secrets/amqp-url/versions/latest"
        fileName: amqp-url.txt
      - resourceName: "projects/shifter-shop/secrets/database-url-users/versions/latest"
        fileName: database-url-users.txt
      - resourceName: "projects/shifter-shop/secrets/database-url-products/versions/latest"
        fileName: database-url-products.txt
      - resourceName: "projects/shifter-shop/secrets/database-url-categories/versions/latest"
        fileName: database-url-categories.txt
      - resourceName: "projects/shifter-shop/secrets/database-url-reviews/versions/latest"
        fileName: database-url-reviews.txt
      - resourceName: "projects/shifter-shop/secrets/database-url-orders/versions/latest"
        fileName: database-url-orders.txt
      - resourceName: "projects/shifter-shop/secrets/database-url-cart/versions/latest"
        fileName: database-url-cart.txt
      - resourceName: "projects/shifter-shop/secrets/database-url-profiles/versions/latest"
        fileName: database-url-profiles.txt
      - resourceName: "projects/shifter-shop/secrets/database-url-inventory/versions/latest"
        fileName: database-url-inventory.txt
      - resourceName: "projects/shifter-shop/secrets/stripe-private-key/versions/latest"
        fileName: stripe-private-key.txt
      - resourceName: "projects/shifter-shop/secrets/stripe-public-key/versions/latest"
        fileName: stripe-public-key.txt
      - resourceName: "projects/shifter-shop/secrets/stripe-webhook-key/versions/latest"
        fileName: stripe-webhook-key.txt
  secretObjects:
    - secretName: jwt
      type: Opaque
      data:
        - key: jwt-secret
          objectName: jwt-secret.txt
    - secretName: mailer
      type: Opaque
      data:
        - key: mailer-dsn
          objectName: mailer-dsn.txt
    - secretName: amqp
      type: Opaque
      data:
        - key: amqp-url
          objectName: amqp-url.txt
    - secretName: database
      type: Opaque
      data:
        - key: url-users
          objectName: database-url-users.txt
        - key: url-products
          objectName: database-url-products.txt
        - key: url-categories
          objectName: database-url-categories.txt
        - key: url-reviews
          objectName: database-url-reviews.txt
        - key: url-orders
          objectName: database-url-orders.txt
        - key: url-cart
          objectName: database-url-cart.txt
        - key: url-profiles
          objectName: database-url-profiles.txt
        - key: url-inventory
          objectName: database-url-inventory.txt
    - secretName: stripe
      type: Opaque
      data:
        - key: private-key
          objectName: stripe-private-key.txt
        - key: public-key
          objectName: stripe-public-key.txt
        - key: webhook-key
          objectName: stripe-webhook-key.txt
