build-client:
  stage: build
  image: node:18
  script:
    - cd client
    - npm ci --cache .npm --prefer-offline
    - npm run build
  cache:
    key:
      files:
        - client/package-lock.json
    paths:
      - client/node_modules
      - client/.npm
  only:
    - dev
    - main
    - merge_requests

test-client:
  stage: test
  image: node:18
  script:
    - cd client
    - npm ci --cache .npm --prefer-offline
    - npm run test
  cache:
    key:
      files:
        - client/package-lock.json
    paths:
      - client/node_modules
      - client/.npm
  only:
    - dev
    - main
    - merge_requests

deploy-client:
  stage: deploy
  image: node:18
  script:
    - cd client
    - echo "Deploying client"
  cache:
    key:
      files:
        - client/package-lock.json
    paths:
      - client/node_modules
      - client/.npm
  only:
    - dev
    - main
