apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
  labels:
    app: mailer
spec:
  selector:
    matchLabels:
      app: mailer
  template:
    metadata:
      labels:
        app: mailer
    spec:
      containers:
        - name: mailer
          image: mailhog/mailhog
          ports:
            - containerPort: 1025
            - containerPort: 8025
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"

---
apiVersion: v1
kind: Service
metadata:
  name: mailer
spec:
  selector:
    app: mailer
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8025
      targetPort: 8025
      nodePort: 30025
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
