# This file is used to create Secret & ConfigMap resources in your local cluster.
# It should never be used in production.
# Copy this file to secrets.yml and replace the values with your own.
# Then run `kubectl apply -f secrets.yml` to create the resources in your cluster.

apiVersion: v1
kind: ConfigMap
metadata:
  name: app
data:
  client-url: <value>
  admin-url: <value>
  api-url: <value>

---
apiVersion: v1
kind: Secret
metadata:
  name: app
type: Opaque
stringData:
  jwt-secret: "jwt-secret"

---
apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  url-users: "postgres://postgres:password@postgres:5432/users"
  url-products: "postgres://postgres:password@postgres:5432/products"
  url-categories: "postgres://postgres:password@postgres:5432/categories"
  url-reviews: "postgres://postgres:password@postgres:5432/reviews"
  url-orders: "postgres://postgres:password@postgres:5432/orders"
  url-cart: "postgres://postgres:password@postgres:5432/cart"
  url-profiles: "postgres://postgres:password@postgres:5432/profiles"
  url-inventory: "postgres://postgres:password@postgres:5432/inventory"

---
apiVersion: v1
kind: Secret
metadata:
  name: amqp
type: Opaque
stringData:
  amqp-url: "amqp://rabbitmq:5672"

---
apiVersion: v1
kind: Secret
metadata:
  name: mailer
type: Opaque
stringData:
  mailer-dsn: <value>

---
apiVersion: v1
kind: Secret
metadata:
  name: stripe
type: Opaque
stringData:
  private-key: <value>
  public-key: <value>
  webhook-key: <value>
