apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: maherydock77/shifter-shop.api
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              memory: "256Mi"
          env:
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: client_url
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database_url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app
                  key: jwt_secret
            - name: MAILER_DSN
              valueFrom:
                secretKeyRef:
                  name: mailer
                  key: mailer_dsn
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: private_key
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: public_key
            - name: STRIPE_WEBHOOK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: webhook_key

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  labels:
    name: api
spec:
  rules:
    - host: api.shiftershop.pro
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: api
                port:
                  number: 3000
