apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-manager
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/shifter-shop/secrets/jwt-secret/versions/latest"
        fileName: jwt-secret.txt
      - resourceName: "projects/shifter-shop/secrets/database-url/versions/latest"
        fileName: database-url.txt
      - resourceName: "projects/shifter-shop/secrets/mailer-dsn/versions/latest"
        fileName: mailer-dsn.txt
      - resourceName: "projects/shifter-shop/secrets/stripe-private-key/versions/latest"
        fileName: stripe-private-key.txt
      - resourceName: "projects/shifter-shop/secrets/stripe-public-key/versions/latest"
        fileName: stripe-public-key.txt
      - resourceName: "projects/shifter-shop/secrets/stripe-webhook-key/versions/latest"
        fileName: stripe-webhook-key.txt
  secretObjects:
    - data:
        - key: jwt-secret
          objectName: jwt-secret.txt
      secretName: jwt-secret
      type: Opaque
    - data:
        - key: database-url
          objectName: database-url.txt
      secretName: database-url
      type: Opaque
    - data:
        - key: mailer-dsn
          objectName: mailer-dsn.txt
      secretName: mailer-dsn
      type: Opaque
    - data:
        - key: stripe-private-key
          objectName: stripe-private-key.txt
      secretName: stripe-private-key
      type: Opaque
    - data:
        - key: stripe-public-key
          objectName: stripe-public-key.txt
      secretName: stripe-public-key
      type: Opaque
    - data:
        - key: stripe-webhook-key
          objectName: stripe-webhook-key.txt
      secretName: stripe-webhook-key
      type: Opaque
