apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc
  labels:
    app: auth-svc
spec:
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      containers:
        - name: auth-svc
          image: maherydock77/shifter-shop.auth-svc
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app
                  key: jwt_secret
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth-svc
  ports:
    - port: 3000
      targetPort: 3000
