apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-svc
  labels:
    app: invoice-svc
spec:
  selector:
    matchLabels:
      app: invoice-svc
  template:
    metadata:
      labels:
        app: invoice-svc
    spec:
      containers:
        - name: invoice-svc
          image: maherydock77/shifter-shop.invoice-svc
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-svc
spec:
  selector:
    app: invoice-svc
  ports:
    - port: 3000
      targetPort: 3000
