apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-svc
  labels:
    app: mailer-svc
spec:
  selector:
    matchLabels:
      app: mailer-svc
  template:
    metadata:
      labels:
        app: mailer-svc
    spec:
      containers:
        - name: mailer-svc
          image: maherydock77/shifter-shop.mailer-svc
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: MAILER_DSN
              valueFrom:
                secretKeyRef:
                  name: mailer
                  key: mailer-dsn
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: amqp
                  key: amqp-url
---
apiVersion: v1
kind: Service
metadata:
  name: mailer-svc
spec:
  selector:
    app: mailer-svc
  ports:
    - port: 3000
      targetPort: 3000
