apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-svc
  labels:
    app: payment-svc
spec:
  selector:
    matchLabels:
      app: payment-svc
  template:
    metadata:
      labels:
        app: payment-svc
    spec:
      containers:
        - name: payment-svc
          image: maherydock77/shifter-shop.payment-svc
          env:
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: client_url
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: private_key
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: public_key
            - name: STRIPE_WEBHOOK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: webhook_key
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: amqp
                  key: amqp_url
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: payment-svc
  ports:
    - port: 3000
      targetPort: 3000
