apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-svc
  labels:
    app: payment-svc
spec:
  selector:
    matchLabels:
      app: payment-svc
  template:
    metadata:
      labels:
        app: payment-svc
    spec:
      containers:
        - name: payment-svc
          image: registry.gitlab.com/shifter-shop/shifter-shop/payment-svc
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: client-url
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: private-key
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: public-key
            - name: STRIPE_WEBHOOK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: webhook-key
            - name: AMQP_URL
              valueFrom:
                secretKeyRef:
                  name: amqp
                  key: amqp-url
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
spec:
  selector:
    app: payment-svc
  ports:
    - port: 3000
      targetPort: 3000
