apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-svc
  labels:
    app: search-svc
spec:
  selector:
    matchLabels:
      app: search-svc
  template:
    metadata:
      labels:
        app: search-svc
    spec:
      containers:
        - name: search-svc
          image: registry.gitlab.com/shifter-shop/shifter-shop/search-svc
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: search-svc
spec:
  selector:
    app: search-svc
  ports:
    - port: 3000
      targetPort: 3000
