# This file is used to create Secret & ConfigMap resources in your local cluster.
# It should never be used in production.
# Copy this file to secrets.yml and replace the values with your own.
# Then run `kubectl apply -f secrets.yml` to create the resources in your cluster.

apiVersion: v1
kind: ConfigMap
metadata:
  name: app
data:
  client_url: <value>
  admin_url: <value>
  api_url: <value>

---
apiVersion: v1
kind: Secret
metadata:
  name: app
type: Opaque
stringData:
  jwt_secret: "jwt-secret"

---
apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  database_url: "postgres://postgres:password@postgres/app"

---
apiVersion: v1
kind: Secret
metadata:
  name: mailer
type: Opaque
stringData:
  mailer_dsn: "smtp://mailer:1025"

---
apiVersion: v1
kind: Secret
metadata:
  name: stripe
type: Opaque
stringData:
  private_key: <value>
  public_key: <value>
  webhook_key: <value>
