apiVersion: apps/v1
kind: Deployment
metadata:
  name: stripe
  labels:
    app: stripe
spec:
  selector:
    matchLabels:
      app: stripe
  template:
    metadata:
      labels:
        app: stripe
    spec:
      containers:
        - name: stripe
          image: stripe/stripe-cli:v1.13.12
          command:
            - "stripe"
            - "listen"
            - "--forward-to"
            - "http://api:3000/stripe/webhook"
          env:
            - name: STRIPE_DEVICE_NAME
              value: shifter_shop_docker
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: private_key
